# Frontend
FROM node:18 AS build
WORKDIR /app
COPY AirportClient/package*.json ./
RUN npm install
COPY AirportClient/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist/airport-client /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80