# Frontend
FROM node:18 AS build
WORKDIR /app
COPY Airport.Client/package*.json ./
RUN npm install
COPY Airport.Client/ .
RUN npm run build --omit=dev

FROM nginx:alpine
COPY --from=build /app/dist/airport-client /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80