global using Airport.Contracts.Helpers;
global using Airport.Contracts.Providers;
global using Airport.Domain.Repositories;
global using Airport.Models.DTOs;
global using Airport.Models.Entities;
global using AutoMapper;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using MongoDB.Bson;
